#    -*- mode: org -*-
#+TITLE: Netzwächterlein
#+AUTHOR: Andreas Wurzer
#+EMAIL: andreas.wurzer@novum-ccservices.at
#+OPTIONS: toc:nil num:nil
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+OPTIONS: reveal_center:nil
#+OPTIONS: reveal_keyboard:t reveal_overview:t
#+REVEAL_TRANS: linear
#+REVEAL_THEME: solarized
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Title">
* Wer?
  - Andreas Wurzer
  - Java Entwickler bei der Novum am Tag
  - "Alles außer Java" Entwickler in der Nacht
* Was?
  - Überwachung Internetverfügbarkeit
  - Einschränkung: Raspberry Pi
** Himbeer Kuchen?
   Bild von RPI
   - Computer in Kreditkartengröße ab 25€
   - Niedriger Stromverbrauch
   - https://www.raspberrypi.org
* Warum?
  - Erleichterung der Fehlersuche
  - Erlernen neuer Techniken
* Wie?
  #+BEGIN_SRC ditaa :file images/netzwaechterlein.png
     Sensoren                                 Endpunkte

 /------\
 |      |                                    +---------+
 |      v          Nachrichtenkanal     +--->| Browser |
 |    :ping -+                          |    |         |
 |           |    +-----------------+   |    +---------+
 |           +--->+ :ping :dns ...  +---+
 |           |    +-----------------+   |    +---------+
 |    :dns --+                          |    |{s}      |
 |           |                          +--->|   DB    |
 |     ... --+                          |    +---------+
 |      |                               |
 \------/                               +---> ...
Periodische
  Abfrage
  #+END_SRC
  #+BEGIN_NOTES
- Periodische Überprüfungen
 - Ping
 - DNS Lookup
- Persistierung
 - Datenbank
- Darstellung
 - Browser
  - Aktueller Zustand
  - Auswertungen
  - Statistiken
- Andere Endpunkte
 - SMS bei Ausfall
  #+END_NOTES
** Nachrichten
   Erfolg
   #+BEGIN_SRC clojure
{:type :dns :status :ok :timestamp 1445021224910}
   #+END_SRC
   Fehler
   #+BEGIN_SRC clojure
{:type :ping :status :error :message "Timeout" :timestamp 1445021225127}
   #+END_SRC
* Technik
  - Plattform: Node.js
  - Sprache: ClojureScript
** Node.js
   - Läuft am Raspberry Pi
   https://nodejs.org
   #+BEGIN_NOTES
Weniger ressourcenintensiv als Java
   #+END_NOTES
** ClojureScript
   Logo von ClojureScript
   - LISP Dialekt
   - wird nach JavaScript übersetzt
   https://github.com/clojure/clojurescript
   #+BEGIN_NOTES
Parentheses
   #+END_NOTES
   #+BEGIN_NOTES
nicht der einzige Vertreter
unter anderem CoffeeScript, TypeScript, Scala
   #+END_NOTES
* Live Demo
* Fragen?!
* Danke für die Aufmerksamkeit
  https://github.com/andeee/netzwaechterlein
